config/routes.rb
Images888::Application.routes.draw do

  get "tag_system/process"

  get "tag_system/index"

  resources :items

  get "images/index"

  get "welcome/index"
  get "welcome/scrape"
  get "welcome/cleanup"
  
  match '/about', to: 'items#about'
  match '/tagcloud', to: 'items#tagcloud'
  match '/terms', to: 'items#terms'

  match 'tag_system' => 'tag_system#index', :as => 'tag_system'
  match 'tagged' => 'items#tagged', :as => 'tagged'

  get "tag_system/process"

  root :to => 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :pictures
	attr_accessible :tag_list
	acts_as_taggable
	acts_as_taggable_on :categorys, :sources

end

app/controllers/items_controller.rb
# encoding: utf-8

class ItemsController < ApplicationController

  # GET /items
  # GET /items.json
   def index
    @search = Item.search(params[:q])
    
    @holder = @search.result.order("created_at DESC").limit(20)

    @items = @search.result.order("created_at DESC").page(params[:page]).per_page(20)
    #@items2 = @search.result.order("created_at DESC").page(params[:page]).per_page(1)


    #@items = Item.order("created_at DESC").page(params[:page]).per_page(40)
    @tmp2 = Item.all

    @numberofrows = Item.count + Picture.count + (3*Item.count)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
      format.js
    end
  end


  def tagged
      if params[:tag].present?
      @tmp = params[:tag]
      @items = Item.tagged_with(params[:tag]).order("created_at DESC").page(params[:page]).per_page(40)
      elsif params[:source].present? 
      @items = Item.tagged_with(params[:source]).order("created_at DESC").page(params[:page]).per_page(40)
      @tmp = params[:source]
    elsif params[:category].present? 
      @items = Item.tagged_with(params[:category]).order("created_at DESC").page(params[:page]).per_page(40)
      @tmp = params[:category]
    else 
      #@items = Item.postall.page(params[:page]).per_page(40)
      @items = Item.first
    end  
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  def tagcloud
  end

  def terms
    @var = "Is 'Paranormal Activity 4' The Best Yet? Frightened Fans Weigh InNew ‘Wreck-It Ralph’ Clip'Star Trek Into Darkness' Teaser is NOT Being Unveiled on FacebookArnold Schwarzenegger's 'Total Recall' Book Debuts to Soft SalesLars von Trier Veterans Willem Dafoe, Udo Kier Complete 'Nymphomaniac' Cast ‘Paranorman’ and ‘Coraline’ Studio Laika Announces a 2014 Release  Seal Team Six: The Raid on Osama Bin Laden 'Geronimo' Clip + ‘Hungry Hungry Hippos: The Movie’ Is Really Happening"

    #@test =  @var.match(/'[^']*'/)
     @test = Array.new
     @test = @var.scan(/‘[^’]*’| '[^']*'/)
      @test.each do |s|
        s.strip!
        s[0] = ''
        s.chop!
      end

      # setup your API key
      Tmdb.api_key = ""

      # setup your default language
      Tmdb.default_language = "en"

      @movie = TmdbMovie.find(:title => "Iron Man", :expand_results => false, :limit => 1)

      

  end

  def about
     @search = Item.search(params[:q])
    @items = @search.result.order("created_at DESC").page(params[:page]).per_page(20)
    #@items = Item.order("created_at DESC").page(params[:page]).per_page(40)
    @tmp2 = Item.all


  end

end

app/helpers/items_helper.rb
module ItemsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_area :keywords %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :article_url %><br />
    <%= f.text_field :article_url %>
  </div>

  <%= f.label :categorys %>
  <%= f.text_field :category_list %>

  <%= f.label :sources %>
  <%= f.text_field :source_list %>

  <%= f.label :tags %>
  <%= f.text_field :tag_list %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
  <%- item.pictures.each do |image| %>


	  <div class = 'inneritem'>
	  		<%= link_to image_tag(image.url.to_s),item,  :class=>"various", "data-fancybox-type" =>"iframe"  %>
	  		
	          <!--<%= link_to image_tag(image.url.to_s, :title => item.created_at.to_s+ ' ' + item.title.strip + '..."'), item %>
	          <%= link_to image_tag(image.url.to_s, :title => item.created_at.to_s+ ' ' + item.title.strip + '..."'), image.url.to_s %>-->
	          <!--<a href= <%= image.url.to_s %> class="fancybox" rel="gallery" title="Sample title 1"><img src=<%= image.url.to_s %> /></a> 
	           <a class="various" data-fancybox-type="iframe" href='/items/1179'><img src=<%= image.url.to_s %> /></a>-->	         

	  </div>
  <% end %>

app/views/items/about.html.erb


<!--

<a href="large_1.jpg" class="fancybox" rel="gallery" title="Sample title 1"><img src="small_1.jpg" /></a>
<a href="http://www.joblo.com/newsimages1/JB_Box_Office_final.jpg" class="fancybox" rel="gallery" title="Sample title 1"><img src="http://www.joblo.com/newsimages1/JB_Box_Office_final.jpg" /></a>


<%= will_paginate @items %>

<div class = 'items' id ='items'>
<%= render @items %>
</div>

-->

app/views/items/about.js.erb
$(document).ready(function() {
  $("a.fancybox").fancybox();
});

/*var $container = $('#items')

var $items = $( "<%= escape_javascript(render(@items)) %>" );
$container.append($items);
$container.imagesLoaded( function () {
  $container.masonry( "appended", $items, true );
});


<% if @items.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript(will_paginate(@items)) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>



var $container = $('#items');

$container.imagesLoaded( function(){
  $container.masonry({
    itemSelector : '.inneritem'
  });
});


//$('#items').append('<%= escape_javascript(render(@items)) %>');
$container.append('<%= escape_javascript(render(@items)) %>').masonry( 'appended', '<%= escape_javascript(render(@items)) %>' );

<% if @items.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript(will_paginate(@items)) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>


*/

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p>Currently <%= Item.count %> news items with <%= Picture.count %> images at <%= @numberofrows %> rows</p> 


<%=  will_paginate @items %>

<div class = 'items' id ='items'>
<%= render @items %>
</div>

app/views/items/index.js.erb
var $container = $('#items')

var $items = $( "<%= escape_javascript(render(@items)) %>" );
$container.append($items);
$container.imagesLoaded( function () {
  $container.masonry( "appended", $items, true );
  	$(".various").fancybox({
		maxWidth	: 800,
		maxHeight	: 600,
		fitToView	: false,
		width		: '70%',
		height		: '70%',
		autoSize	: false,
		closeClick	: false,
		openEffect	: 'none',
		closeEffect	: 'none'
	});
});


<% if @items.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript(will_paginate(@items)) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 0.5 %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<% images = @item.pictures %>



<% images.each do |image|  %>

  <div class = 'item2'>
    <%= link_to image_tag(image.url.to_s, :title => @item.created_at.to_s+ ' ' + @item.title.strip + '..."'), image.url.to_s %>
  </div>
  <% end %>


<div class='basic-info'
<p>
  <b>Title:</b>
  <%= @item.title %>
</p>

<p>
  <b>Article url:</b>
  <%= link_to 'link to article', @item.article_url %>
</p>

<% @item.categorys.any? %>
        <% @item.categorys.each do |category| %>
        <%= link_to category.name, tagged_url(:category => category.name) %>
<% end %>

<% @item.sources.any? %>
        <% @item.sources.each do |source| %>
        <%= link_to source.name, tagged_url(:source => source.name) %>
<% end %>

<% @item.tags.any? %>
        <% @item.tags.each do |tag| %>
        <%= link_to tag.name, tagged_url(:tag => tag.name) %>
<% end %>
<p></p>
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

</div>

app/views/items/tagcloud.html.erb
<div id="tag_cloud">
  <% tag_cloud Item.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, 'tagged?tag='+tag.name, class: css_class %>
  <% end %>
</div>


app/views/items/tagged.html.erb
<p>There are <%= @items.count %> news items tagged with <%= @tmp %> </p>

<%= will_paginate @items %>

<div class = 'items' id ='items'>
<%= render @items %>
</div>

app/views/items/tagged.js.erb
$('#items').append('<%= escape_javascript(render(@items)) %>');
<% if @items.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript(will_paginate(@items)) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/items/terms.html.erb
<p> <%= @movie %> </p>

<h1> <%= @var %> </h1>

<% @test.each do |s| %>
<h3> <%= s %> </h3>
<% end %>