config/routes.rb
Images888::Application.routes.draw do

  get "tag_system/process"

  get "tag_system/index"

  resources :items

  get "images/index"

  get "welcome/index"
  get "welcome/scrape"
  get "welcome/cleanup"
  
  match '/about', to: 'items#about'
  match '/tagcloud', to: 'items#tagcloud'
  match '/terms', to: 'items#terms'

  match 'tag_system' => 'tag_system#index', :as => 'tag_system'
  match 'tagged' => 'items#tagged', :as => 'tagged'

  get "tag_system/process"

  root :to => 'items#index'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container2">
      <nav>

        <ul class="nav pull-left">
          <div class="btn-toolbar">

            <div class="btn-group">
             <div class="btn btn-link" data-toggle="dropdown">Category</div>
                <div class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                 <% @categorylist.each do |i| %>
                 <li><%= link_to i.name, "tagged?category=" + i.name %><li>
                 <% end %>
              </div>  
            </div>

            <div class="btn-group">
             <div class="btn btn-link" data-toggle="dropdown">Source</div>
                <div class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                 <% @sourcelist.each do |i| %>
                 <li><%= link_to i.name, "tagged?source=" + i.name %><li>
                 <% end %>
              </div>  
           </div>


            <div class ="btn-group">
              <%= search_form_for @search do |f| %>
              <%= f.text_field :title_cont, :class =>"input-medium search-query" %>
              <button type="submit" class="btn btn-small btn-danger">Search</button>
              <% end %> 
            </div>

          </div>        
        </ul>

        <ul class="nav pull-right">
          <div class="dropdown" id ="rightMenuBtn">
            <div class="btn btn-small btn-info" data-toggle="dropdown"></div>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
             <li> <%= link_to 'Home', root_path %></li>
             <li> <%= link_to 'About', about_path %></li>
             <li> <%= link_to 'Tag cloud', tagcloud_path %></li>
             <li> <%= link_to 'Terms', terms_path %></li>
            </ul>
          </div>
        </ul>

      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Images888</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>    

</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fixed">
      <%= yield %>
    </div>
  </body>
</html>